### ISSUE TITLE
Running unit tests  : unknown import path "engine": cannot find module providing package engine

### ISSUE THREAD

**Issue by michaelhidalgo** [0xrawsec/gene#6]
Hey @qjerome , I'm trying to run the gene unit test for the engine but I'm having some trouble.

Am I missing something?

**go test engine_test.go**

``` [root@mike engine] **go test engine_test.go**

engine_test.go:5:2: unknown import path "engine": cannot find module providing package engine
FAIL    command-line-arguments [setup failed]

[root@mike engine]
```

**Comment by qjerome** [comment]
Hi @michaelhidalgo, no you are not missing anything. It is my mistake when I refactored the project to be go1.12 modules friendly. It will be fixed in the next commit. Though it should work if you remove the line where the error is. Let me know if it does not, I will rush finishing my work pending for the next commit.

**Comment by qjerome** [comment]
Fixed in master
